spring:
  datasource:
    url: jdbc:h2:mem:database
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: prinroomescapeprinroomescapeprinroomescapeprinroomescapeprinroomescapeprinroomescape
  expiration: 36000000
